### PR TITLE
FIX: Issue 2 set up GitHub bot to make branches

### PR DESCRIPTION
**Pull request by ctmes**
Working auto-create branching bot
- tested on my own test repo, working

### CODE REVIEW

**Comment by SodaVolcano** [comment]
@ctmes are the assignees for reviewing your PR? If so I've reassigned them under reviewers instead of assignees

**Comment by ctmes** [comment]
> @ctmes are the assignees for reviewing your PR? If so I've reassigned them under reviewers instead of assignees

Ahh yeah thanks

**Review by SodaVolcano — APPROVED** [review]
Wow that's really quick. Looks good to me :+1:

**Review by Reece030130 — COMMENTED** [review]
good!

**Review by Reece030130 — APPROVED** [review]

**Pull request merged**
